#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'nose==1.3.7','console_scripts','nosetests-3.4'
__requires__ = 'nose>=1.3.7'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point(
            'nose>=1.3.7', 'console_scripts', 'nosetests-3.%s' %
                sys.version_info.minor)()
    )
