#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'nose==0.10.4','console_scripts','nosetests'
__requires__ = ['nose>=0.10.4']
import sys
from pkg_resources import load_entry_point

import nose.core
from utils.perfplugin import PerfPlugin

nose.core.main(addplugins=[PerfPlugin()])
