# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# If adding new functions to this file, note that you can add help text to the function
# by defining a variable with name _<function>_help containing the help text

export PAGURE_CONFIG=~/pagure.cfg

pstart (){
    systemctl --user start pagure.service pagure-docs.service pagure_ci.service\
        pagure_ev.service pagure_webhook.service
}

pstop (){
    systemctl --user stop pagure.service pagure-docs.service pagure_ci.service\
        pagure_ev.service pagure_webhook.service
}

prestart (){
    systemctl --user restart pagure.service pagure-docs.service pagure_ci.service\
        pagure_ev.service pagure_webhook.service
}

pstatus (){
    systemctl --user restart pagure.service pagure-docs.service pagure_ci.service\
        pagure_ev.service pagure_webhook.service
}
